### ISSUE TITLE
Log analysis python unit tests fail with Python3.8

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther#763]
### Describe the bug

My laptop recently upgraded python to 3.8, and now just one unit test is consistently failing. Not high priority yet, but once Lambda supports Python 3.8, we'll want to upgrade and then we'll need to fix this

### Steps to reproduce

1. Upgrade Python 3.8.2
2. `mage test:ci`
3. See error message:

```
======================================================================
FAIL: test_add_overflows_buffer (rules_engine.tests.test_output.TestMatchedEventsBuffer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/austin/go/src/github.com/panther-labs/panther/internal/log_analysis/rules_engine/tests/test_output.py", line 319, in test_add_overflows_buffer
    DDB_MOCK.update_item.assert_called_once()
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/mock.py", line 892, in assert_called_once
    raise AssertionError(msg)
AssertionError: Expected 'update_item' to have been called once. Called 0 times.

----------------------------------------------------------------------
```

### Expected behavior

Unit tests pass with Python 3.8

**Comment by kostaspap** [comment]
Closing this. Panther runs on Python3.7 now. Will come back to fix this once we migrate to 3.8
